<?php
/**
 * Copyright (c) 2025 Fusion Lab G.P
 * Website: https://fusionlab.gr
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/** @var \FusionLab\SkroutzAnalytics\Block\Head $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<!-- START SKROUTZ ANALYTICS -->

<script type="text/javascript" nonce="<?php echo $block->getCspNonce(); ?>">
    (function (a, b, c, d, e, f, g) {
        a['SkroutzAnalyticsObject'] = e;
        a[e] = a[e] || function () {
            (a[e].q = a[e].q || []).push(arguments);
        };
        f = b.createElement(c);
        f.async = true;
        f.src = d;
        g = b.getElementsByTagName(c)[0];
        g.parentNode.insertBefore(f, g);
    })(window, document, 'script', 'https://skroutza.skroutz.gr/skroutza.min.js', 'skroutz_analytics');
    skroutz_analytics('session', 'connect', '<?php echo $escaper->escapeHtml($block->getAccountId());?>');
</script>
<!-- END START SKROUTZ ANALYTICS -->
